server:
  port: 8085
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-vehiculo-service
          uri: lb://ms-vehiculo-service
          predicates:
            - Path=/vehiculo/**
          filters:
            - AuthFilter
        - id: ms-cliente-service
          uri: lb://ms-cliente-service
          predicates:
            - Path=/clientes/**
          filters:
            - AuthFilter
        - id: ms-registroenvio-service
          uri: lb://ms-registroenvio-service
          predicates:
            - Path=/registroenvio/**
          filters:
            - AuthFilter
        - id: ms-librocarga-service
          uri: lb://ms-librocarga-service
          predicates:
            - Path=/librocarga/**
        - id: ms-gestionenvio-service
          uri: lb://ms-gestionenvio-service
          predicates:
            - Path=/gestionenvio/**
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**